//
//  ResponseInterceptor.swift
//  FRCore
//

import Foundation


/**
 ResponseInterceptor is an interface that allows developers to implement to intercept Responses and modify the SDK generated Response as needed. Once ResponseInterceptor is implemented, an array of ResponseInterceptor can be registered to `ResponseInterceptorFactory` which then every time that Response is being made from SDK, SDK invokes 'ResponseInterceptor.intercept()' method to allow modification of that particular response.
 */
public protocol ResponseInterceptor {
    
    /// Intercepts Response that is received by SDK, modifies, and returns updated Response if needed
    /// - Parameters:
    ///   - request: Original Response object generated by SDK
    ///   - action: Action represents a type of the request that is currently being made
    func intercept(response: Response, action: Action) -> Response
}
