name: CI

# Trigger on push or pull request
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master
      - develop

jobs:
  # Build and run unit tests
  build-and-test:
    name: Build and test
    uses: ./.github/workflows/build-and-test.yaml
    secrets:
      CONFIG_E2E_CLOUD: ${{secrets.CONFIG_E2E_CLOUD}}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # # Run Mend CLI Scan
  # mend-cli-scan:
  #   name: Mend CLI Scan
  #   uses: ./.github/workflows/mend-cli-scan.yaml
  #   secrets:
  #     MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
  #     MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
  #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
  
  # Build BrowserStack test artifacts
  browserstack-prepare-artifacts:
    name: Prepare device farm artifacts
    uses: ./.github/workflows/browserstack-prepare-artifacts.yaml
    # needs: build-and-test
    secrets:
      CERTIFICATES_FILE_BASE64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
      CERTIFICATES_PASSWORD: ${{ secrets.CERTIFICATES_PASSWORD }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      BUILD_PROVISION_PROFILE: ${{ secrets.BUILD_PROVISION_PROFILE_ZIP_BASE64}}
      CONFIG_E2E_CLOUD: ${{secrets.CONFIG_E2E_CLOUD}}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  
  # Execute e2e test cases in BrowserStack.
  browserstack-run:
    name: Run e2e tests in BrowserStack
    uses: ./.github/workflows/browserstack-run.yaml
    needs: browserstack-prepare-artifacts
    secrets:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # Wait for BrowserStack test run to finish and publish results
  browserstack-results:
    name: Wait for BrowserStack test results
    uses: ./.github/workflows/browserstack-results.yaml
    needs: browserstack-run
    secrets:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      browserstack-build-id: ${{ needs.browserstack-run.outputs.build_id }}